	"logout":"loguit",
    "statusstatu":"Home",//"Status",
	"profile":"Profiel",
	"account":"Account",
	"fxs_port":"FXS Poort",
	"fxo_port":"FXO Poort",
	"fxs":"FXS",
	"fxo":"FXO",
	"fxs1":"FXS 1",
	"fxs2":"FXS 2",
	"fxo1":"FXO 1",
	"fxo2":"FXO 2",
	"fax_mode":"Fax Mode",
	"T38":"T38",
	"pass_through":"Pass Through",
	"off_hook_dial": "Hoorn van de haak automatisch kiezen",
	"fax_tone_detect": "Fax Toon Detectie Mode",
	"bell_style_conference":"Gebruik Bell-style 3-weg Conferentie",
	"DistinctiveRingTone":"Onderscheidend belsignaal",
	"caller_id":"Oproepnummer:",
	"loop_current_dis":"Loop Current Disconnect",
	"loop_current_dis_dur":"Loop Current Disconnect Duration",
	"auto":"Auto",
	"caller":"Caller",
	"callee":"Callee",
	"fxs_impedance":"FXS Impedantie",
	"caller_id_scheme":"Caller ID Scheme",
	"onhook_vol":"Onhook Voltage",
	"PolarityReversal":"ompoling",
	"ring_tone1":"Belsignaal 1",
	"ring_tone2":"Belsignaal 2",
	"ring_tone3":"Belsignaal 3",
	"ring_tone4":"Belsignaal 4",
	"ring_tone5":"Belsignaal 5",
	"ring_tone6":"Belsignaal 6",
	"ring_tone7":"Belsignaal 7",
	"ring_tone8":"Belsignaal 8",
	"ring_tone9":"Belsignaal 9",
	"ring_tone10":"Belsignaal 10",
	"hunting":"Hunt Groep (Hetzelfde als FXS Poort 1)",
	"login":"Login",
	"loginerr":"Sorry. Uw Wachtwoord wordt niet herkend. Probeer het opnieuw.",
	"network":"Netwerk",
	"dsskey":"Functie toetsen",
	"phone" :"Instellingen",
	"contacts":"Tel. boek",
	"security":"Service",
    //
	"status":"Status",
	"account_basic":"Basic",
	"profile_basic":"Basic",
	"codec":"Codec",
	"advanced":"Geavanceerd",
    //"planet_ddns":"DDNS instelling",  添加到最后，方便客户翻译
	"memory_key":"Geheugen Toets",
	"line_key":"Regel Toets",
	"programmable_key":"Progr.<br />Toets",
	"exp_key":"Uitbr. Module",
	"preference":"Voorkeur",
	"upgrade":"Upgrade",
	"features":"Opties",
	"auto_provision":"Auto<br /> Provisioning",
	"configuration":"Configuratie",
	"voice":"Spraak",
	"ring":"Belsignaal",
	"tones":"Tonen",
	"sms":"SMS",
	"action_url":"Actie URL",
	"softkey_layout":"Softtoets<br />Lay-out",
    //intercom
	"keypad":"Toetsenbord",
	"camera":"Camera",
	"lcd":"LCD",
//    "doorphone":"Door phone",
	"relay":"Relay",
	"open_dtmf":"Open DTMF",
	"close_dtmf":"Sluit DTMF",
	"open_duration":"Open duur",
	"talk_duration":"Spreek duur",
	"remote_password":"Extern wachtwoord",
	"local_password":"Lokaal wachtwoord",
//    "unlock_door_beep":"Unlock door beep",
	"relay_beep":"Relay piep",
	"long_beeps":"Lange piep",
	"short_beeps":"Korte piep",
	"keypad_mode":"Toetsenbord mode",
	"dial_password":"Dial&password",
	"only_password":"Alleen wachtwoord",
	"enable_keypad":"Inschakelen toetsenbord",
	"enable_access_table":"Enable access table",
	"enable_rfid_card":"Enable RFID card",
	"enable_camera":"Enable camera",
	"door_phone_server":"Door phone server",
	"key1_dialnumber":"Speed dial number",
	"key2_dialnumber":"Speed dial number 2",
	"rfid":"RFID",
	"rfid1":"RFID 1",
	"rfid2":"RFID 2",
	"rfid3":"RFID 3",
	"rfid4":"RFID 4",
	"rfid5":"RFID 5",
	"rfid6":"RFID 6",
	"rfid7":"RFID 7",
	"room":"Room",
//    "number":"Nummer",
//    "mobie":"Mobiel",
	"phone1":"Phone 1",
	"phone2":"Phone 2",
	"access_code":"Toegangs Code",
//    "user_type":"User Type",
	"guest":"Guest",
	"administrator":"Administrator",
	"access_table":"Toegangs Tabel",
	"loss_table":"Loss Table",
	"import_access_table":"Import Table",
	"export_access_table":"Export Table",
	"move_to_access":"Verplaats naar toegang/verlies",
	"read_rfid":"Lees RFID",
	"tr069":"TR069",
	"tr069_enable":"TR069 Inschakelen ",
	"acs_username":"ACS Gebruikersnaam",
	"acs_password":"ACS Wachtwoord",
	"acs_url":"ACS URL",
	"enable_periodic_inform":"Schakel periodiek informeren in",
	"periodic_inform_interval":"Periodieke Informatie Interval (seconden)",
	"periodic_inform_interval_question":"Integer from 5 to 2147483647",
	"connection_request_username":"Verbinding verzoekt om gebruikersnaam",
	"connection_request_password":"Verbinding verzoekt om wachtwoord",
	"preference_tr069":"Set the TR069.",
	"contacts_left":"Contacten",
	"ldap":"LDAP",
	"remote_phonebook":"Extern Telefoonboek",
	"phone_call_info":"Phone Call Info",
	"broadsoft":"BroadSoft",
	"network_dir":"Netwerk Telefoonboek",
	"alcatel":"Alcatel",
	"calllog":"Calllog",
	"vlan":"VLAN",
	"qos":"QoS",
	"local_rtp_port":"Lokale RTP Poort",
	"tls_certs":"Vertrouwd CA",
	"tls_server_certs":"Server CA",
	"import_tls_certs_file":"Importeer vertrouwde certificaatbestanden",
	"import_server_certs_file":"Importeer certificatenbestanden van de server",
	"tls_certs_file":"TLS-certificaatbestand (SIP)",
    //status
	"version_middle":"Versie",
	"image_version":"Image Versie",
	"major_version":"Major Versie",
	"minor_version":"Minor Versie",
	"firmware_version":"Firmware Versie",
	"network_middle":"Netwerk",
	"wan_port_type":"WAN Poort Type",
	"wan_ip_address":"WAN IP Adres",
	"gateway":"Gateway",
	"vpn_address":"VPN adres",
	"mac_address":"MAC adres",
	"system_up_time":"Uptime van het systeem",
	"device_type":"Apparaat type",
	"account1":"Account1",
	"account2":"Account2",
	"account3":"Account3",
	"account4":"Account4",
	"account5":"Account5",
	"account6":"Account6",
	"account7":"Account7",
	"account8":"Account8",
	"account9":"Account9",
	"account10":"Account10",
	"account11":"Account11",
	"account12":"Account12",
	"account13":"Account13",
	"account14":"Account14",
	"account15":"Account15",
	"account16":"Account16",
    //account
	"save_set":"Opslaan",
	"cancel":"Annuleer",
	"english":"Engels",
	"chinese":"Chinees",
	"why1":"Kies webtaal.",
	"why2":"Selecteer lokale tijd zone",
	"why3":"Selecteer DHCP Optie 2 voor het netwerk om deze de tijdzone-instelling overschrijven toe te staan",
	"why4":"Indien ingesteld op automatisch, zal de zomertijd 1 uur vooruit lopen io de wintertijd; indien ingesteld op inschakelen, kan de gebruiker de tijden voor begin zomertijd, en begin wintertijd zelf aanpassen",
	"why5":"Selecteer de indeling voor de weergave van de datum",
	"why6":"Inschakelen of uitschakelen van toetsenbord DTMF-tonen",
	"why7":"De bestandsnaam mag alleen letters en cijfers bevatten en onderstrepen '_' personen, en de afbeelding aantal mag niet meer dan 8 karakters bevatten",
	"introduction_of_dhcpoption100":"DHCP-optie 100 heeft de hoogste prioriteit, hoger dan de DHCP-tijd en de tijdzone",
	"way1":"Jaar - Maand - Dag",
	"way2":"Maand - Dag - Jaar",
	"way3":"Dag - Maand - Jaar",
	"question_mask1":"Primaire (eerste) SIP server, b.v.: sip.provider.nl:poort, of IP adres:poort",
	"question_mask2":"Optioneel, gebruik dit domein wanneer de primary server niet reageerd",
	"question_mask3":"Ja - Registreert zich naar de primaire server als de Failover-registratie vervalt",
	"question_mask4":"Uitgaande Proxy server (indien platform dit vereist), b.v.: proxy.provider.nl:poort, of IP adres:poort. (Laat leeg indien niet opgegeven door provider)",
	"question_mask5":"Transport van de RTP stream, standaard is UDP ingesteld",
	"question_mask6":"De gebruikersnaam of registratienaam bijhorend bij het SIP account",
	"question_mask7":"De authenticatienaam bijhorend bij het account, vaak is deze identiek aan de SIP Gebruikers ID, informeer bij uw provider indien men niet zeker is",
	"question_mask8":"Wachtwoord van het SIP account",
	"question_mask9":"De lokale accountnaam die op de andere telefoon wordt weergegeven wanneer u belt",
	"question_mask10":"Tijd waarin registratie verloopt. Deze wordt in minuten opgegeven. Standaard waarde is 15 minuten",
	"question_mask11":"SIP Poort, standaard 5060",
	"question_mask12":"1024-65535, standaard 5004",
	"question_mask13":"Telefoonnummer wat gekozen moet worden om de Voice Mail te bereiken",
	"question_mask14":"Wanneer de telefoon is gestart, wordt dit bericht verzonden.",
	"question_mask15":"Wanneer een account met succes is geregistreerd, wordt het bericht verzonden.",
	"question_mask16":"Wanneer een geregistreerde account is aangemeld, wordt het bericht verzonden.",
	"question_mask17":"Wanneer een accountregistratie mislukt, wordt het bericht verzonden.",
	"question_mask18":"Wanneer de oproep wordt aangenomen, wordt het bericht uitgestuurd.",
	"question_mask19":"Als de oproep wordt be&euml;ndigt, wordt het bericht uitgestuurd.",
	"question_mask20":"Als de telefoon een inkomend gesprek ontvangt, wordt het bericht verzonden.",
	"question_mask21":"Wanneer de telefoon een uitgaande oproep maakt, wordt het bericht verzonden.",
	"question_mask22":"Wanneer een oproep is opgebouwd, wordt het bericht uitgestuurd.",
	"question_mask23":"Wanneer een gesprek is beëindigd, wordt het bericht verzonden.",
	"question_mask24":"Wanneer DND (Niet storen) is ingeschakeld, wordt het bericht verzonden.",
	"question_mask25":"Wanneer DND (Niet storen) is uitgeschakeld, wordt het bericht verzonden.",
	"question_mask26":"Als de functie Altijd oproep doorschakelen direct is ingeschakeld, wordt het bericht uitgestuurd.",
	"question_mask27":"Wanneer u de functie oproep doorschakelen direct uitschakelt, wordt het bericht uitgestuurd.",
	"question_mask28":"Wanneer de functie oproep doorschakelen bij bezet actief is, wordt het bericht verzonden.",
	"question_mask29":"Als de functie oproep doorschakelen bij bezet actief is uitgeschakeld, wordt het bericht verzonden.",
	"question_mask30":"Wanneer de functie oproep doorschakelen bij geen antwoord is ingeschakeld, wordt het bericht verzonden.",
	"question_mask31":"Wanneer de functie oproep doorschakelen bij geen antwoord is uitgeschakeld, wordt het bericht verzonden.",
	"question_mask32":"Wanneer de telefoon een overdracht doet (bijwonen / doorverbinden / blind doorverbinden), wordt het bericht verzonden.",
	"question_mask33":"Wanneer de telefoon een oproep voor blind doorverbinden maakt, wordt het bericht verzonden.",
	"question_mask34":"Wanneer de telefoon doorverbind met ruggespraak maakt, dan wordt het bericht verzonden.",
	"question_mask35":"Wanneer u een gesprek in de wachtstand plaatst, wordt het bericht uitgestuurd.",
	"question_mask36":"Bij het opnemen van een gesprek in de wacht, wordt het bericht verzonden",
	"question_mask37":"Als u een gesprek muteert, wordt het bericht uitgestuurd.",
	"question_mask38":"Als u geen gesprek heeft, dan wordt het bericht verzonden.",
	"question_mask39":"Zelfs als de gemiste oproeplogboeken uitgeschakeld zijn. Als er een nieuw gemist oproep is, wordt het bericht verzonden.",
	"question_mask40":"Idle to Busy",
	"question_mask41":"Busy to Idle",
    "question_mask42":"Doorsturen van de inkomende oproep",//Forward  Incoming Call
    "question_mask43":"Weigeren van de inkomende oproep",//Reject  Incoming Call
    "question_mask44":"Beantwoord de nieuwe inkomende oproep",//Answer  New Incoming Call
    "question_mask45":"Overdracht succesvol",//Transfer Finished
    "question_mask46":"Overdracht mislukt",//Transfer Failed
	"question_mask47":"Indien Ja, wordt een Flash verzonden als een DTMF-gebeurtenis",
	"question_mask48":"Indien Ja, worden oproepfuncties met behulp van stercodes lokaal ondersteund",
	"question_mask49":"Gebruik NAT vermelding in SIP/SDP bericht",
	"question_mask50":"Stop belsignaal na 10-300 seconden, de standaard waarde is 60 seconden",
	"question_mask51":"Indien ingesteld op Ja, zal '#' functioneren als de '(Re-) Dial' toets",
	"question_mask52":"Het uitgaande nummer wordt geblokkeerd indien ingesteld op Ja",
	"question_mask53":"In seconden, standaard is 180 seconden",
	"question_mask54":"In seconden. standaard en minimum is 90 seconden",
	"question_mask55":"Indien ingesteld op 'Ja' en de externe partij ondersteunt sessie-timers, gebruikt de telefoon een sessie-timer wanneer het een uitgaand gesprekken plaatst.",
	"question_mask56":"Indien ingesteld op 'Ja' en de externe partij ondersteunt sessie-timers, gebruikt de telefoon een sessie-timer wanneer deze een inkomende oproep ontvangt.",
	"question_mask57":"Als Forceer Timer is ingesteld op 'Ja', gebruikt de telefoon de sessie-timer, zelfs als de externe partij deze functie niet ondersteunt. Als Forceer Timer is ingesteld op 'Nee', activeert de telefoon alleen de sessie-timer wanneer de externe partij deze functie ondersteunt. Om de sessie-timer uit te schakelen, selecteer 'Nee'.",
	"question_mask58":"De sessie-timer kan worden vernieuwd met de INVITE-methode of de UPDATE-methode. Selecteer 'Ja' om de INVITE-methode te gebruiken, en om de sessie-timer te vernieuwen.",
	"question_mask59":"Opmerking: in het bereik van 50-1200 milliseconden",
	"question_mask60":"Configuratie bestand zou worden geverifieerd voor acceptatie indien ingesteld op Ja",
	"question_mask61":"De intervaltijd moet 0-720 dagen zijn",
	"question_mask62":"BroadSoft Groep",
	"question_mask63":"BroadSoft Display Naam",
	"question_mask64":"BroadSoft Server",
	"question_mask65":"BroadSoft Server Poort Nummer",
	"question_mask66":"BroadSoft Server Gebruikersnaam",
	"question_mask67":"BroadSoft Server Wachtwoord",
	"question_mask68":"Oproeplogboek Groep",
	"question_mask69":"Oproeplogboek Display Naam",
	"question_mask70":"Oproeplogboek Server",
	"question_mask71":"Oproeplogboek server poort nummer",
	"question_mask72":"Oproeplogboek Server Gebruikersnaam",
	"question_mask73":"Oproeplogboek Server Wachtwoord",
	"question_mask74":"op tot 10/20/30/40/50/60 voor G711/G726/G723/andere codecs respectievelijk",
	"question_mask75":"Zet de toon voor onderscheidend belsignaal",
	"question_mask76":"Syntax: f1=freq@vol, f2=freq@vol, c=aan1/uit1-aan2/uit2-aan3/uit3; [...]",
	"question_mask77":"Indien ingesteld op Ja, wordt het cfg-bestand door de telefoon geverifieerd voordat deze wordt geaccepteerd",
	"question_mask78":"standaard:f1=440,f2=480,c=200/400",
	"question_mask79":"Diff-Serv of Precedence waarde",
	"question_mask80":"Alleen geldig als in de bridge modus",
	"question_mask81":"URI van IP:poort",
	"question_mask82":"Seconden (Standaard 20)",
	"question_mask83":"De standaard waarde voor de Web Server is 80",
	"question_mask84":"IP adres dynamisch toegewezen via een DHCP server",
    "question_mask85":"Vast IP-adres opgeven",//Specify the  IP address
	"question_mask86":"Neem contact op met uw netwerkbeheerder of serviceprovider om te weten of deze instelling moet worden gebruikt",
	"question_mask87":"PC Poort instellen als Bridge mode",
	"connect_expansion_note":"Als deze modus is ingesteld, dan kan men via het IP toestel op de PC Poort, de uitbreidingsmodule aansluiten",
	"question_mask88":"PC Poort instellen als Router mode",
	"question_mask89":"Als de ingave letters zijn, gaat het apparaat zoeken naar de contacten op de server.",
	"question_mask90":"Als de ingave cijfers zijn, gaat het apparaat zoeken naar de contacten op de server.",
	"question_mask91":"LDAP-serveradres (de waarde kan een domeinnaam of IP-adres zijn)",
    "question_mask92":"LDAP server poort",//LDAP server port
	"question_mask93":"Zoek de hoofdmap van de server",
	"question_mask94":"Gebruikersnaam om in te loggen op de server",
	"question_mask95":"Wachtwoord om in te loggen op de server",
	"question_mask96":"Het maximale aantal zoekresultaten",
	"question_mask97":"Het type weergave naam van de zoekresultaten",
	"question_mask98":"De tijd om de zoekresultaten weer te geven na het invoeren van zoekinformatie",
	"question_mask99":"De versie van het protocol",
	"question_mask100":"Bepaalt of u een weergavenaam wilt zoeken voor een inkomende oproep met LDAP",
	"question_mask101":"sorteer de resultaten",
	"question_mask102":"Geeft de huidige firmware versie van de telefoon weer",
	"question_mask103":"Toont de registratie status van de accounts",
	"question_mask104":"Geeft de details van de netwerk configuratie van de telefoon weer",
	"question_mask105":"Stel oproepdoorschakeling in",
	"question_mask106":"Bestemmings nummer naar waar de doorschakeling dient plaats te vinden",
	"question_mask107":"De feature code die de telefoon stuurt om doorsturen voor alle inkomende gesprekken mogelijk te maken.",
	"question_mask108":"De feature code die de telefoon stuurt om het doorsturen van alle inkomende gesprekken uit te schakelen",
	"question_mask109":"Overgebracht naar bestemmings nummer",
	"question_mask110":"De feature code die de telefoon stuurt om het gesprek door te zetten op de knop",
	"question_mask111":"De feature code die de telefoon stuurt om het gesprek vooruit te drukken op te zetten",
	"question_mask112":"Wachttijd voor oproepdoorschakeling bij-geen-antwoord (indien ingeschakeld); Bereik: 6-120 seconden, standaard = 60 sec.",
	"question_mask113":"Bestemmings nummer naar waar de doorschakeling dient plaats te vinden",
	"question_mask114":"De feature code die de telefoon stuurt om oproepdoorschakeling bij-geen-antwoord in te schakelen",
	"question_mask115":"De feature code die de telefoon stuurt om oproepdoorschakeling bij-geen-antwoord uit te schakelen",
	"question_mask116":"De feature code die de telefoon stuurt om DND in te stellen (niet storen)",
	"question_mask117":"De feature code die de telefoon stuurt om DND uit te schakelen (Niet storen)",
	"question_mask118":"In seconden; 0 betekent nooit geen time-out, standaard is 0 seconden",
	"question_mask119":"Schakel de aangepaste Softtoets-functie in/uit",
	"question_mask120":"Selecteer de Oproep status die de softtoetsen kunnen aanpassen",
	"question_mask121":"Schakel de toetsen uit",
	"question_mask122":"Niet geselecteerde softtoets",
	"question_mask123":"Toetsen inschakelen",
	"question_mask124":"Geselecteerde softtoets(en) (gesorteerd op positie) **",
	"question_mask130":"De laagste RTP Poort: Poort >= 1024",
	"question_mask131":"De grootste RTP Poort: Moet groter zijn dan (Min-RTP-poort + 100) en minder dan 65535",
	"question_mask132":"Backup uitgaande Proxy server (indien Uitgaande Proxy niet reageerd), b.v.: proxy.provider.nl:poort, of IP adres:poort. (Laat leeg indien niet opgegeven door provider)",
	"question_mask133":"Als deze optie is ingeschakeld, wordt bij een actief gesprek en een inkomend intercomgesprek het vorige gesprek in de wacht gezet en wordt het intercomgesprek beantwoord",
	"question_mask134":"Laat DHCP-optie 42 toe om de waardes van de NTP-server te overschrijven",
	"question_mask135":"NTP Server Adres",
    "question_mask136":"Stel het tijdsformaat in op 12 uurs of 24 uurs notificatie",//Set time as 12-hour or 24-hour
	"question_mask137":"Als ingeschakeld, analyseert de telefoon RTP Info-statistieken en rapporteert u indien nodig naar Collector",
	"question_mask138":"Het SIP-adres van de RTCP Collector, bijvoorbeeld: sip:account@voorbeeld.nl:8765",
	"question_mask139":"Het formaat van de rapportage publiceert Info",
	"question_mask140":"Schakel de verzendingsaanvragen van de telefoon aan/uit op de server om de URL te verkrijgen voor het downloaden van firmware-updates",
	"question_mask141":"Indien Ja is geselecteerd, start de telefoon de ZRTP-sessie met het peer-eindpunt (per RFC 6189)",
	"question_mask142":"Configureert de verificatie voor toegang tot het eXtended Services Interface (XSI) -platform",
	"question_mask143":"Configureert het IP-adres of domeinnaam van de eXtended Services Interface (XSI) -platformserver voor account X",
	"question_mask144":"Configureert het poortnummer van de XSI-platformserver voor account X",
	"question_mask145":"Configureert het toegangsprotocol van de XSI-platformserver voor account X",
	"question_mask146":"Configureert de gebruikersnaam voor XSI-verificatie voor account X",
	"question_mask147":"Configureert het wachtwoord voor XSI-verificatie voor account X",
	"question_mask148":"Configureert de gebruikersnaam voor UC-verificatie",
	"question_mask149":"Configureert het wachtwoord voor UC-verificatie.",
	"question_mask150":"Schakelt de IP-telefoon in of uit, om de groepsmappen weer te geven en de weergavenaam op het LCD-scherm voor de groepsmappen te configureren.",
	"question_mask151":"Schakelt de IP-telefoon in of uit om de bedrijfs directory weer te geven en configureert de weergavenaam op het LCD-scherm voor de bedrijfs directory.",
	"question_mask152":"Schakelt de IP-telefoon in of uit om de algemene map van de groep weer te geven en de weergavenaam op het LCD-scherm voor de gemeenschappelijke map van de groep te configureren.",
	"question_mask153":"Schakelt de IP-telefoon in of uit, om de algemene bedrijfsmaatschappij weer te geven en de weergavenaam op het LCD-scherm in te stellen voor de algemene bedrijfsmaatschappij.",
	"question_mask154":"Schakelt de IP-telefoon in of uit om de persoonlijke map weer te geven en configureert de weergavenaam op het LCD-scherm voor de persoonlijke map.",
	"question_mask155":"Schakelt de functie voor aangepaste directory in of uit",
	"question_mask156":"Schakelt de BroadSoft-oproeplogboekfunctie in of uit",
	"question_mask157":"Configureert het verstrijken van de vervaltijd (in seconden) voor account X. De IP-telefoon kan de SUBSCRIBE succesvol vernieuwen voor het verstrijken van de SIP registratie",
	"question_mask158":"Schakelt de BroadSoft SCA Barge-In functie in of uit",
	"question_mask159":"Indien ingeschakeld, zal snelkies / BLF overeenkomen met de getallen",
	"question_mask160":"Indien ingeschakeld, wordt de SIP NOTIFY Event Check_sync geverifieerd",
	"question_mask161":"Reverse polariteit bij oproep vestiging en beëindiging",
	"question_mask162":"Indien Ja, zal *23 worden uitgeschakeld",
	"question_mask163":"Draai de huidige ontkoppeling bij de beëindiging van de oproep",
	"question_mask164":"In 100 - 10000 milliseconden reeks, standaard is 200",
	"question_mask165":"Syntax: c=aan1/uit1-aan2/uit2-aan3/uit3; [...]",
	"question_mask166":"EAP-TLS:importeer .pem bestand",
	"question_mask167":"EAP-TLS: importeer .pem-bestand met zowel certificaat als privé sleutel",
	"question_mask168":"In- of uitschakelen van de MWI indicatie voor het voicemailnummer, toegewezen aan account X",
    //添加到最后，方便后续多语言定制
	"dhcp_server":"DHCP server",
	"save":"Opslaan",
	"delete1":"Wis",
    "move_to_blacklist":"Verplaats naar Blacklist",//Move To Black List
	"default1":"Standaard",
	"develop":"Develop",
	"office":"Kantoor",
	"sales":"verkoop",
	"n_a":"Niet beschikbaar",
	"j_m":"JM",
	"add":"Toevoegen",
	"edit":"Bewerk",
	"search1":"Zoeken",
	"delete_all":"Alles wissen",
	"delete_photo":"Wis afbeelding",
	"upload_photo":"Upload afbeelding",
	"import_local_contacts":"Importeer Lokale Contacten",
	"import_xml":"Import XML",
	"export_xml":"Export XML",
	"import_csv":"Import Csv",
	"export_csv":"Export Csv",
	"account_1":"Account 1",
	"account_2":"Account 2",
	"account_3":"Account 3",
	"account_4":"Account 4",
	"account_5":"Account 5",
	"account_6":"Account 6",
	"account_7":"Account 7",
	"account_8":"Account 8",
	"account_9":"Account 9",
	"account_10":"Account 10",
	"account_11":"Account 11",
	"account_12":"Account 12",
	"account_13":"Account 13",
	"account_14":"Account 14",
	"account_15":"Account 15",
	"account_16":"Account 16",
	"profile_1":"Profiel 1",
	"profile_2":"Profiel 2",
	"profile_3":"Profiel 3",
	"profile_4":"Profiel 4",
	"profile_5":"Profiel 5",
	"profile_6":"Profiel 6",
	"send_keep_alive":"Nee, maar stuur, keep alive",
	"stun":"STUN",
	"a_record":"A Record",
	"srv":"SRV",
	"naptr_srv":"NAPTR/SRV",
	"fixed1":"Vast",
	"adaptive":"Aangepaste",
	"low":"Laag",
	"high":"Hoog",
	"medium":"Midden",
	"system_ring_tone":"Standaard",
	"custom_ring_tone1":"Ring1.bin",
	"custom_ring_tone2":"Ring2.bin",
	"custom_ring_tone3":"Ring3.bin",
	"custom_ring_tone4":"Ring4.bin",
	"custom_ring_tone5":"Ring5.bin",
	"custom_ring_tone6":"Ring6.bin",
	"custom_ring_tone7":"Ring7.bin",
	"custom_ring_tone8":"Ring8.bin",
	"no_send":"Nee, stuur geen SUBSCRIBE voor voicemail indicatie",
	"yes_send":"Ja, stuur periodieke SUBSCRIBE voor voicemail indicatie",
	"uac":"UAC",
	"uas":"UAS",
	"omit":"Weglaten (Aanbevolen)",
	"uas1":"UAS (Wanneer UAC geen vernieuwingscode heeft opgegeven)",
	"minimum":"minimum:",
	"maximum":"maximum:",
	"standard":"Standaard",
	"nethid":"NETHID",
	"world_call":"Wereldoproep",
	"yes_http":"Ja, HTTP",
	"yes_tftp":"Ja, TFTP",
	"yes_ftp":"Ja, FTP",
	"yes_https":"Ja, HTTPS",
	"broadsoft1":"BroadSoft 1",
	"broadsoft2":"BroadSoft 2",
	"broadsoft3":"BroadSoft 3",
	"broadsoft4":"BroadSoft 4",
	"broadsoft5":"BroadSoft 5",
	"broadsoft6":"BroadSoft 6",
	"user1":"Gebruiker",
	"calllog_item":"Oproeplogboek Item",
	"calllog1":"Oproeplogboek 1",
	"calllog2":"Oproeplogboek 2",
	"calllog3":"Oproeplogboek 3",
	"current_setting":"Huidige instelling is ",
	"choose1":"G.723.1",
	"choose2":"G.729A/B",
	"choose3":"PCMU",
	"choose4":"PCMA",
	"choose5":"G.726-32",
	"choose6":"G.722 (wide band)",
	"choose7":"GSM_FR",
	"kbps63":"6.3kbps Codering rate",
	"kbps53":"5.3kbps Codering rate",
	"download":"Download",
	"download_xml":"Download XML Bestand",
	"download_Bin":"Download BIN Bestand",
	"restore_configuration":"Herstel Configuratie",
	"debug":"DEBUG",
	"warning":"WAARSCHUWING",
	"error":"FOUT",
	"none":"GEEN",
	"info1":"INFO",
	"import1":"Importeer",
	"have_no_data":"War_HaveNoData",
	"reset_to_factory":"Reset",
	"start":"Start",
	"stop1":"Stop",
	"export1":"Export.",
	"import_tls_certificate":"Importeer vertrouwde certificaten",
	"import_server_certificate":"Importeer server certificaten",
	"send":"Stuur",
	"admin":"Admin",
	"click_to_relogin":"Klik hier om opnieuw in te loggen",
    "phone_book_url":"Telefoonboek URL",//Phone Book UEL
	"one":"1",
	"two":"2",
	"three":"3",
	"four":"4",
	"five":"5",
	"reset_to_default":"Reset naar standaard waarden",
	"dB1":"+6dB",
	"dB2":"+4dB",
	"dB3":"+2dB",
	"dB0":"0dB standaard",
	"dB4":"-2dB",
	"dB5":"-4dB",
	"dB6":"-6dB",
	"min0":"uit",
	"min1":"1 min",
	"min2":"2 min",
	"min3":"5 min",
	"min4":"10 min",
	"min5":"30 min",
	"min6":"60 min",
	"min7":"20 min",
	"exp_screensaver_mode":"Uitbreidingsmodule screensaver tijd",
	"backlight_off":"Achtergrondverlichting uit",
	"time_logo":"tijd & logo",
	"time_only":"Alleen tijd",
	"photo_switch":"Willekeurig",
	"disable":"Uitgeschakeld",
	"enable":"Ingeschakeld",
	"time_range":"(15~3600s)",
	"eap_md5":"EAP-MD5",
	"eap_tls":"EAP-TLS",
	"attended_transfer":"Aangekondigd doorverbinden",
	"blind_tansfer":"On-aangekondigd doorverbinden",
	"new_call":"Nieuwe oproep",
	"web_server":"Web server",
	"x8021":"802.1X",
	"x8021_mode":"802.1X Mode",
	"ca_certificates":"CA-certificaten",
	"device_certificates":"Apparaatcertificaten",
	"http_and_https":"HTTP&HTTPS",
	"http_only":"Alleen HTTP",
	"https_only":"Alleen HTTPS",
	"call_switch":"Oproepschakelaar",
	"reset_default":"Reset naar standaard waarden",
	"ring_tone":"Belsignalen",
	"screen_photo":"Screensaver afbeelding",
	"custom_softkey":"Aangepaste softtoets",
	"broadsoft_sca":"Broadsoft SCA",
	"bla":"BLA",
	"connect_mode":"Verbindings Mode",
	"reliable_retransmission":"100 Reliable Retransmission",
	"early_session":"Early-Session",
	"refuse_return_code":"Weiger-Return-code",
	"NOT_FOUND_404":"404 (Niet gevonden)",
	"BUSY_486":"486 (Bezet)",
	"REFUSE_480":"480 (Tijdelijk niet beschikbaar)",
	"Caller_Display_Source":"Nummerweergave display bron",
	"from_only":"Alleen From",
	"PAI_FROM":"PAI-FROM",
	"PAI_RPID_FROM":"PAI-RPID-FROM",
	"RPID_PAI_FROM":"RPID-PAI-FROM",
	"RPID_FROM":"RPID-FROM",
	"static_dns":"Statisch DNS",
	"paging_codec":"Multicast codec",
	"pnp_active":"PnP aktief",
	"phone_lock":"Vergrendeling telefoon",
	"keypad_lock":"Toetsenbord vergrendeling",
	"phone_unlock_pin":"PIN voor ontgrendeling (0~15 cijfers)",
	"auto_lock_time_out":"Automatisch vergrendelen Time-out (15~3600s)",
	"emergency":"Noodoproep",
	"display_mode":"Display Mode",
	"icon_mode":"Icoon Mode",
	"text_mode":"Tekst Mode",
	"call_wait":"Aankloppen",
	"call_waiting":"Aankloppen",
	"call_waiting_tone":"Aanklop Toon",
	"dialing":"Kiezen",
	"connecting":"Verbinden",
	"semi_attend_trans":"Doorverbinden met Ruggespraak",
	"semi_attend_trans_back":"Doorverbinden zonder ruggespraak",
	"call_failed":"Oproep mislukt",
	"call_in":"Oproep in",
	"talk":"Spreek",
	"held":"Held",
	"pretrans":"Tijdens doorverbinden",
	"conferenced":"Tijdens conferentie gesprek",
	"d_pickup":"DPickup",
	"g_pickup":"GPickup",
	"pool":"Pool",
	"more":"Meer",
	"split1":"Splitsen",
	"resume":"Hervatten",
	"conference":"Conferentie",
	"swap":"SWAP",
	"cc":"CC",
	"transfer":"Doorverbinden",
	"reject":"Afwijzen",
	"silence":"Stilte",
	"answer":"Beantwoord",
	"directory":"Telefoonboek",
	"history":"Lijsten",
	"ime":"IME",
	"forward1":"Oproepdoorschakelen",
	"call_states":"Oproep Status",
	"tag":"Prompt",
	"tag_fort":"De velden * moeten worden ingevuld (vereist een herstart van de telefoon)",
	"tag_fort1":"De velden * moeten worden ingevuld (vereist een herstart van de telefoon)",
	"restart_system":"Systeem Herstart",
	"reboot_system":"Systeem Reboot",
	"operate_sucessed":"Bezig, even geduld ...",
	"operate_restart":"Herstarten  ...",
	"operate_reboot":"Rebooting  ...",
	"operate_update":"Updaten  ...",
	"operate_wait":"Wacht ongeveer 20 seconden voordat u de telefoon opnieuw kan gebruiken!",
	"reboot_wait":"Wacht ongeveer 40 seconden voordat u de telefoon opnieuw kan gebruiken! ",
	"update_wait":"Wacht ongeveer 1 minuut voor de telefoon om te updaten!",
	"update_fail":"Upgrade fout! Controleer het firmware bestand!",
	"account_middle":"Account",
	"profile_middle":"Profiel",
	"account_active":"Account Aktief",
	"account_status":"Account Status",
	"sip_server":"Primaire SIP Server",
	"FailoverServer":"Failover SIP Server",
	"SecondFailoverServer":"Tweede Failover SIP Server",
	"PreferPrimaryServer":"Voorkeurs primaire SIP Server",
	"outbound_proxy":"Uitgaande Proxy",
	"sip_transport":"SIP Transport",
	"sip_user_id":"SIP Gebruikers ID",
	"user_id":"Gebruikers ID",
	"authenticate_id":"Authenticatie ID",
	"authenticate_password":"Authenticatie Wachtwoord",
	"dns_mode":"DNS mode",
	"user_id_as_number":"Gebruikers ID is telefoonnummer",
	"sip_registration":"SIP Registratie",
	"unregister_on_reboot":"De-registratie bij een reboot",
	"register_expiration":"Registratie verlopen",
	"outgoing_call_without":"Uitgaande oproep zonder registratie",
	"use_random_port":"Gebruik willekeurige poort",
	"voice_mail_user_id":"Voice Mail Nummer",
	"intercom_dial_code":"Intercom Kies Code",
	"pick_up_dial_code":"Pick-Up code",
	"dtmf_payload_type":"DTMF Payload Type",
	"dtmf_in_audio":"In Audio",
	"dtmf_via_rfc2833":"RFC2833",
	"dtmf_via_sip_info":"SIP INFO",
	"send_flash_event":"Stuur Flash Event",
	"enable_call_features":"Oproepfuncties inschakelen",
	"hotline_number":"Hotline Nummer",
	"hotline_time_out":"Hotline Time-out(seconden)(0~180s)",
	"proxy_require":"Proxy vereist",
	"use_nat_ip":"Gebruik NAT IP",
	"preferred_vocoder":"Gewenste audio codecs (in volgorde weergegeven):",
	"preferred_choice1":"Keuze 1:",
	"preferred_choice2":"Keuze 2:",
	"preferred_choice3":"Keuze 3:",
	"preferred_choice4":"Keuze 4:",
	"preferred_choice5":"Keuze 5:",
	"preferred_choice6":"Keuze 6:",
	"voice_frames_per_tx":"PTime(ms)",
	"g723_rate":"G723 Rate",
	"account_vad":"VAD Inschakelen",
	"srtp_mode":"SRTP Mode",
	"srtp_disable":"Uitgeschakeld",
	"srtp_enable_unforce":"SRTP ingeschakeld maar niet verplicht",
	"srtp_enable_force":"SRTP ingeschakeld en vereist",
	"zrtp_enc":"ZRTP Encryptie",
	"symmetric_rtp":"Symmetrisch RTP",
	"jitter_buffer_type":"Jitter Buffer type",
	"jitter_buffer_length":"Jitter Buffer lengte",
	"account_ring_tone":"Belsignaal",
	"ring_timeout":"Stop belsignaal",
	"use_as_dial_key":"Gebruik # voor kiezen",
	"dial_plan":"Kies plan",
	"send_anonymous":"Anoniem verzenden",
	"anonymous_call_rejection":"Anonieme Oproep Afwijzing",
	"check_sip_user_id":"Accepteer alleen oproepen v/d SIP server",
	"auto_answer":"Automatisch beantwoorden",
	"allow_auto_answer":"Automatisch antwoord toestaan via oproepinfo",
	"turn_off_speaker":"Zet de luidspreker uit op afstandsbediening",
	"session_espiration":"Sessie vervaltijd",
	"min_se":"Min-SE",
	"caller_request_timer":"Caller Request Timer",
	"callee_request_timer":"Callee Request Timer",
	"force_timer":"Forceer Timer",
	"uac_specify_refresher":"UAC Specificeer Vernieuwing",
	"uas_specify_refresher":"UAS Specificeer Vernieuwing",
	"force_invite":"Forceer Invite",
	"hook_flash_timing":"Haak Flash Timer",
	"special_feature":"Speciale Feature",
	"eventlist_blf_url":"Eventlist BLF URL",
	"lable":"Label",
	"firmware_server_path":"Firmware Server URL",
	"config_server_path":"Config Server URL",
	"allow_dhcp_pption":"Laat DHCP-optie toe",
	"override_server":"Server overschakelen:",
	"auto_upgrade":"AUTO Upgrade:",
	"check_upgrade_minute":"Controleer voor upgrade elke",
	"httpc_username":"HTTP/FTP/HTTPS gebruikersnaam",
	"httpc_password":"HTTP/FTP/HTTPS wachtwoord",
	"upgrade_check_mode":"Upgrade Check Mode :",
	"upgrade_always_check":"Controleer altijd voor nieuwe firmware",
	"check_new_firmware":"Controleer alleen nieuwe firmware wanneer F/W voor achtervoegsel verandert",
	"always_skip_check":"Firmware controle altijd overslaan",
	"authenticate_cfg_file":"Authenticatie CFG Bestand",
	"authenticate_cfg_file_notice":"(Indien ingesteld op Ja, wordt het cfg-bestand geverifieerd voordat het wordt geaccepteerd)",
	"phonebook_xml_download":"Telefoonboek XML Download",
	"phonebook_download":"Telefoonboek Download",
	"phonebook_download_interval":"Telefoonboek Download Interval:",
	"set_common_aes_key":"Algemene AES Sleutel",
	"enable_xml_download":"Telefoonboek Download Inschakelen:",
	"xml_server_path":"Telefoonboek XML Server URL:",
	"remove_manually_edited":"Verwijder handmatig bewerkte vermeldingen op download:",
	"snmp_set":"SNMP Service",
	"snmp_service_enable":"SNMP Service Inschakelen",
	"snmp_get_community":"SNMP Get Community",
	"snmp_set_community":"SNMP Set Community",
	"snmp_manager_ip1":"SNMP manager IP 1",
	"snmp_manager_ip2":"SNMP manager IP 2",
	"snmp_manager_ip3":"SNMP manager IP 3",
	"snmp_manager_ip4":"SNMP manager IP 4",
	"ntp_server":"NTP Server",
	"ntp_server_set1":"NTP Server",
	"ntp_server_set2":"DHCP mag NTP Server overschrijven",
	"distinc_ring_tone":"Onderscheidend belsignaal",
	"distinc_ring_tone_set1":"Aangepaste belsignaal 1, gebruikt als inkomende nummerweergave is",
	"distinc_ring_tone_set2":"Aangepaste belsignaal 2, gebruikt als inkomende nummerweergave is",
	"distinc_ring_tone_set3":"Aangepaste belsignaal 3, gebruikt als inkomende nummerweergave is",
	"distinc_ring_tone_set4":"Systeem Belsignaal",
	"register_name":"Registratie Naam",
	"call_progress_tone":"Overgangs Tonen",
	"call_progress_tone_set1":"Kies Toon",
	"call_progress_tone_set2":"Terugbel Toon",
	"call_progress_tone_set3":"Ingespreks Toon",
	"call_progress_tone_set4":"Reorder Toon",
	"call_progress_tone_set5":"Bevestigings Toon",
	"call_progress_tone_set6":"Aanklop Toon",
	"other_advanced_set":"Andere geavanceerde set",
	"user_name":"Gebruikersnaam",
	"override_mtu_size":"Override MTU Size",
	"lock_keypad_update":"Vergrendel toetsenbord update",
	"syslog_server":"Syslog Server",
	"syslog_level":"Syslog Nivo",
	"volume_amplification":"Volume versterking",
	"screen_timeout":"Scherm Time-Out",
	"screensaver_type":"Screensaver Type",
	"upload_screen_photo":"Upload Screensaver afbeelding",
	"upload_limit":"(De grootte van de afbeelding moet minder zijn dan 2Mb, de lengte van de naam mag niet langer zijn dan 48 karakters)",
	"download_device_Xml_configuration":"Download Apparaat XML Configuratie",
	"download_device_Bin_configuration":"Download Apparaat BIN Configuratie",
	"download_system_log":"Download Systeem Log",
	"reset_to_factory_settings":"Naar Fabrieksinstellingen",
	"restore_xml_configuration":"Importeer XML Configuratie",
	"restore_bin_configuration":"Importeer BIN Configuratie",
	"upgrade_mode":"Upgrade Mode",
	"upgrade_firmware":"ROM Firmware Upgrade",
	"password":"Wachtwoord",
	"blind_transfer_on_hook":"Blind Transfer On Hook",
	"semi_attended_transfer":"Semi-Attended Transfer",
	"attended_transfer_on_hook":"Attended Transfer On Hook",
	"transfer_mode":"Transfer Mode via DSS toets",
	"hold_transfer_on_hook":"Hold Transfer On Hook",
	"call_pickup":"Call Pickup",
	"direct_call_pickup":"Directe Call Pickup",
	"direct_call_pickup_code":"Directe Call Pickup Code",
	"group_call_pickup":"Groep Call Pickup",
	"group_call_pickup_code":"Groep Call Pickup Code",
	"visual_alert_for_blf_pickup":"Visual Alert voor BLF Pickup",
	"audio_alert_for_blf_pickup":"Audio Alert voor BLF Pickup",
	"admin_password":"Admin Wachtwoord",
	"current_password":"Huidig Wachtwoord",
	"new_password":"Nieuw Wachtwoord",
	"confirm_password":"Bevestig Wachtwoord",
	"password_max_len":" (Max lengte 26)",
	"active":"Aktief",
	"packed_interval":"Packet Interval",
	"layer_qos":"Qos Set",
	"layer_3_qos":"Voice Qos",
	"layer_2_qos":"Layer 2 Qos",
	"vlan_tag":"Data VLAN Tag",
	"stun_server":"Stun Server",
	"keep_alive_interval":"Keep-alive Interval",
	"no_key_entry_timeout":"Geen sleutelinvoer time-out (seconden)",
	"firmware_upgrade":"Firmware Upgrade ",
	"port":"Poort",
	"enable_outbound_proxy_server":"Inschakelen Uitgaande Proxy server",
	"outbound_proxy_server":"Uitgaande Proxy server",
	"transport":"Transport",
	"backup_outbound_proxy_server":"Backup Uitgaande Proxy Server",
	"nat_traversal":"NAT Traversal",
	"voice_mail":"Voice Mail",
	"aninymous_call":"Anoniem gesprek",
	"on_code":"Aan code",
	"off_code":"Uit code",
	"missed_call_log":"Gemiste oproepen",
   // "xml_idlescreen_active":"XML ldleScreen Active",
   // "xml_idlescreen_url":"XML ldleScreen URL",
	"audio_codecs":"Audio Codecs",
	"disable_codecs":"Uitschakelen Codecs",
	"udp_keep_alive_message":"UDP keep-alive message",
	"udp_keep_alive_interval_seconds":"UDP keep-alive interval (seconden)",
	"login_expire_seconds":"Login verloopt (seconden)",
	"local_sip_port":"Lokale SIP Poort",
	"sip_session_timer_seconds":"SIP Sessie Timer (seconden)",
	"rport":"RPort",
	"subscribe_period_seconds":"Subscribe Periode (seconden)",
	"dtmf_type":"DTMF Type",
    //"how_to_info_dtmf":"How to INFO DTMF",
	"dtmf_payload_seconds":"DTMF Payload (seconden)",
	"subscribe_register":"Subscribe Register",
	"subscribe_for_mwi":"Registreer voor MWI",
	"mwi_subscription_priod":"MWI Registratie Periode (Scope:0~84600)(seconden)",
	"caller_id_header":"Caller ID Header",
	"use_session_timer":"Gebruik Sessie Timer",
   // "use_use_phone":"Gebruik use=phone",
	"voice_encryption":"Spraak Encryptie",
	"ptime":"ptime (ms)",
	"blf_list_url":"BLF List URL",
	"blf_list_code":"BLF List Code",
	"shared_line":"Shared Line",
	"dialog_lnfo_call_pickup":"Dialog-lnfo Call Pickup",
	"sip_registration_retry_timer":"SIP Registratie Herhaal Timer (Scope:0~1800)(seconden)",
	"enable_signal_encode":"Enable Signal Encode",
	"signal_encode_key":"Signal Encode Toets",
	"conference_type":"Conferentie Type",
	"conference_url":"Conferentie URL",
	"acd_subscription_period":"ACD Registratie Periode (120~3600)",
	"Subscribe_MWI_To_Voice_Mail":"Registratie MWI naar Voice Mail",
	"sip_server_type":"SIP Server Type",
	"ConfType":"Conferenctie Type",
	"Network":"Netwerk",
	"Local":"Lokaal",
	"server":"Server",
	"mixed":"Lokaal & Server",
	"ConfURI":"Conferentie URI",
    //network
	"web_port":"Webpoort",
	"PORT_ID": "Poort",
	"wan":"IPv4 instellingen",
	"wan_v6":"IPv6 instellingen",
	"dhcp":"DHCP",
	"identity":"Identiteit",
	"md5_password":"MD5 wachtwoord",
	"static_ip_address":"Statisch IP Adres",
	"dhcp_hostname":"DHCP Hostnaam",
	"dhcp_domain":"DHCP Domein",
	"dhcp_vendor_id":"DHCP Vendor Class ID",
	"dhcp_user_class":"DHCP Gebruikers Classe",
	"ip_address":"IP Adres",
	"subnet_mask":"Subnet Mask",
	"default_gateway":"Standaard Gateway",
	"primary_dns":"Primair DNS",
	"secondary_dns":"Secundair DNS",
	"pppoe":"PPPoE",
	"user":"Gebruikersnaam",
	"PPPoE_Password":"Wachtwoord",
	"PPPoE_Service_Name":"Service Naam",
	"PPPoE_DNS_Server":"Voorkeurs DNS server",
	"Cloned_Wan_Mac":"Kloon WAN MAC",
	"lan":"PC poort",
	"as_bridge":"Als bridge",
	"as_expand":"Uitbreidingsmodule",
	"as_router":"Als router",
	"enable_dhcp":"Inschakelen DHCP server",
	"Ip_lease_time":"IP Lease Tijd",
	"wan_port_map":"WAN poort ",
	"lan_IP_map":"LAN IP ",
	"lan_port_map":"LAN poort ",
	"protocol_map":"Protocol ",
	"start_ip_address":"Start IP adres",
	"end_ip_address":"Eind IP adres",
	"dmz_ip":"DMZ IP",
	"port_map":"Poort Mapping",
	"replay_icmp":"Reageer op ICMP",
	"wan_http_access":"WAN HTTP toegang",
	"user_password":"Wachtwoord",
	"basic_cfg_password":"Gebruiker wachtwoord",
	"no":"Nee",
	"yes":"Ja",
	"lldp":"LLDP",
	"wan_port":"WAN poort",
	"vid":"VID",
	"priority":"Prioriteit",
	"pc_port":"PC poort",
	"vpn":"VPN",
	"vpnactive":"VPN aktief",
	"upload_vpn_config":"Upload VPN Config",
	"voice_qos":"Voice QoS",
	"localrtp_port":"Lokale RTP Poort",
	"maxrtpport":"Max RTP Poort",
	"minrtpport":"Min RTP Poort",
	"webserver":"Web Server",
	"http_port":"HTTP Poort",
	"https_port":"HTTPS Poort",
	"type":"Type",
	"key":"Toets",
	"value":"Waarde",
	"line":"Lijn",
	"extension":"Pickup code",
	"label":"Label",
	"mode":"Mode",
	"line_key1":"Toets 1",
	"line_key2":"Toets 2",
	"line_key3":"Toets 3",
	"line_key4":"Toets 4",
	"line_key5":"Toets 5",
	"line_key6":"Toets 6",
	"line_key7":"Toets 7",
	"line_key8":"Toets 8",
	"line_key9":"Toets 9",
	"line_key10":"Toets 10",
	"line_key11":"Toets 11",
	"line_key12":"Toets 12",
	"line_key13":"Toets 13",
	"line_key14":"Toets 14",
	"line_key15":"Toets 15",
	"line_key16":"Toets 16",
	"line_key17":"Toets 17",
	"line_key18":"Toets 18",
	"line_key19":"Toets 19",
	"line_key20":"Toets 20",
	"line_key21":"Toets 21",
	"line_key22":"Toets 22",
	"line_key23":"Toets 23",
	"line_key24":"Toets 24",
	"line_key25":"Toets 25",
	"line_key26":"Toets 26",
	"line_key27":"Toets 27",
	"line_key28":"Toets 28",
	"line_key29":"Toets 29",
	"line_key30":"Toets 30",
	"line_key31":"Toets 31",
	"line_key32":"Toets 32",
	"line_key33":"Toets 33",
	"line_key34":"Toets 34",
	"line_key35":"Toets 35",
	"line_key36":"Toets 36",
	"default":"Standaard",
	"lock":"Lock",
	"float":"Drijvend",
	"line_page_indicator":"Lijn Pagina Indicator",
	"line_label_length":"Lijn Label Lengte",
	"long_label":"Lange Label",
	"medium_label":"Medium Label",
	"multi_page_mode":"Multi Pagina Mode",
	"blf_auto_cfg":"BLF list Mode",
	"manual":"Handmatig",
	"automatically":"Automatisch",
	"dds_key1":"Toets 1",
	"dds_key2":"Toets 2",
	"dds_key3":"Toets 3",
	"dds_key4":"Toets 4",
	"dds_key5":"Toets 5",
	"dds_key6":"Toets 6",
	"dds_key7":"Toets 7",
	"dds_key8":"Toets 8",
	"dds_key9":"Toets 9",
	"dds_key10":"Toets 10",
	"softkey1":"Soft toets 1",
	"softkey2":"Soft toets 2",
	"softkey3":"Soft toets 3",
	"softkey4":"Soft toets 4",
	"up":"Omhoog",
	"down":"Omlaag",
	"left":"Links",
	"right":"Rechts",
	"ok":"OK",
	"dsskey_cancel":"Annuleer",
	"conf":"CONF",
	"dsskey_hold":"HOLD",
	"dsskey_mute":"MUTE",
	"tran":"DOORVERB.",
	"undefinedsoftkey1":"Ongedefinieerde Softtoets 1",
	"undefinedsoftkey2":"Ongedefinieerde Softtoets 2",
	"undefinedsoftkey3":"Ongedefinieerde Softtoets 3",
	"undefinedsoftkey4":"Ongedefinieerde Softtoets 4",
	"expkey_font":"Uitbreidingsmodule is niet aangesloten!"+'<br />'+"Sluit een of meerdere uitbreidingsmodules aan,"+'<br />'+"en ververs dan deze pagina.",
    //phone
	"incoming_call_show":"Inkomende oproepweergave modus",
	"logfont_size":"Telefoon lettertype hoogte grootte",
	"watch_dog":"Watch Dog Inschakelen",
	"pixel8":"8 pixels",
	"pixel9":"9 pixels",
	"pixel10":"10 pixels",
	"pixel11":"11 pixels",
	"pixel18":"18 pixels",
	"pixel20":"20 pixels",
	"pixel24":"24 pixels",
	"pixel28":"26 pixels",
	"incoming_pname_pnum":"Peer Naam & Peer Nummer",
	"incoming_pname_pnum_lname":"Peer Naam & Peer Nummer & Eigen Naam",
	"status_led":"LED Status Instelling:",
	"power_status":"Status voeding",
	"ringing_status":"Status belsignaal",
	"miss_calls_status":"Status overige oproepen",
	"web_language":"Webtaal",
	"dhcptime":"DHCP Tijd ",
	"time_zone":"Tijd Zone",
	"system_log":"Systeem Log",
	"cfg_file": "Configuratie bestand",
	"primary_ntp_server":"Primaire NTP Server",
	"secondary_ntp_server":"Secundaire NTP Server",
	"update_interval_seconds":"Update Interval (seconden)",
	"daylight_saving_time":"Zomertijd",
	"time_format":"Tijd formaat",
	"hour_12":"12 Uur",
	"hour_24":"24 Uur",
	"date_display_format":"Datum weergave formaat",
	"key_dtmf_tone":"Toetsenbord DTMF toon",
	"handfree_agc":"Handenvrij (Auto Gain Control)",
	"fixed_type":"Vast Type",
    //"start_month":"Start Month",
    //"start_hour_of_day":"Start Hour of Day",
    //"start_day_of_week":"Start Day of Week",
    //"start_day_of_week_last_in_month":"Start Day of Week Last in Month",
    //"start_month":"Start maand",
    //"stop_date":"Stop Datum",
    //"stop_hour_of_day":"Stop Hour of Day",
    //"stop_hour_of_week":"Stop Hour of Week",
    //"stop_day_of_week_last_in_month":"Stop Day of Week Last in Month",
	"offset":"Offset (minuten)",
	"date":"Datum",
	"year":"Jaar",
	"mouth":"Maand",
	"day":"Dag",
	"time":"Tijd",
	"hour":"Uur",
	"minute":"Minuut",
	"second":"Seconden",
	"date_format":"Datum formaat",
    //"active_backlight_level":"Active Backlight Level",
    //"inactive_backLight_level":"Inactive BackLight Level",
	"backlight_time":"Tijd achtergrondverlichting",
	"phone_time":"Toestel Tijd",
	"keyboard_lock":"Toetsenbord vergrendeling",
	"watchdog":"Watchdog",
	"ring_type":"Belsignaal Type",
	"upload_ringtone":"Upload Belsignaal",
	"screensaver_time":"Screensaver Tijd",
	"singal_encode_key":"Signaal Encode Toets",
	"load_screensaver":"Laad Screeensaver",
	"forward":"Oproepdoorschakeling:",
	"always":"Altijd",
	"on":"Aan",
	"off":"Uit",
	"target":"Bestemmings nummer",
	"busy":"Bij Bezet",
	"no_answer":"Bij Geen Antwoord",
	"after_ring_time":"Na belsignalen (seconden)",
	"phone_dnd":"DND (niet storen)",
	"hotline":"Hotline",
	"transfer_Setting":"Transfer instellingen",
	"transfer_function":"Transfer Mode via Functie toets ",
	"phone_dnd_on":"DND Aan Code",
	"phone_dnd_off":"DND Uit Code",
	"authorized_numbers":" Gemachtigde nr.s (komma's gescheiden)",
	"version":"Versie:",
	"product_type":"Product Model",
	"hardware_version":"Hardware Versie",
	"reset_to_factory_setting":"Reset naar fabrieksinstellingen:",
	"reboot":"Reboot",
	"restart":"Herstart",
	"pcap_feature":"Pcap Feature:",
	"select_and_upgrade_firmware":"Selecteer en Upgrade Firmware:",
    //"pnp_active":"PNP Aktief",
	"dhcp_active":"DHCP Aktief",
	"custom_option":"Aangepaste Optie (128~254)",
	"custom_option_type":"Aangepaste Optie Type",
	"dhcp_option":"DHCP Optie 60",
	"server_url":"Server URL",
	"username":"Gebruikersnaam",
	"common_aes_key":"Gemeenschappelijke AES-sleutel",
	"mac_oriented_aes_key":"MAC-georiënteerde AES-sleutel",
    //"zeroactive":"ZeroActive",
	"waittime":"Wacht tijd",
	"check_new_config":"Controleer Nieuwe Configuratie",
	"repeatedly":"Herhaaldelijk",
	"interval":"Interval (Minuten)",
	"weekly":"Wekelijks",
	"day_of_week":"Dag van de week",
	"sunday":"Zondag",
	"monday":"Maandag",
	"tuesday":"Dinsdag",
	"wednesday":"Woensdag",
	"thursday":"Donderdag",
	"friday":"Vrijdag",
	"saturday":"Zaterdag",
	"export_user_data":"exporteer Gebruikers Data",
	"export_system_log":"Exporteer Systeem Log",
	"local":"Lokaal",
	"systemloglevel":"Systeemlog Nivo",
	"echo_cancellatione":"Echo-annulering",
	"echo_canceller":"Echo canceller",
	"vad":"VAD",
	"gng":"GNG",
	"fixed":"Vast",
	"min_delay":"Min vertraging",
	"max_delay":"Max vertraging",
	"mormal_delay":"Normale vertraging",
	"internal_ringer_text":"Internal Ringer Text",
	"internal_ringer_file":"Internal Ringer File",
	"dial":"Kies",
	"ring_back":"Terug Oproep",
	"congestion":"Congestie",
    //"cial_recall":"Cial Recall",
	"dial_waiting":"Oproep wachten",
	"record":"Opnemen",
	"info":"Info",
    //"stutter":"Stutter",
	"message":"Bericht",
	"number":"Nummer",
	"setup_completed":"Setup Compleet",
	"log_on":"Geregistreerd",
	"log_off":"Niet Geregistreerd",
	"register_failed":"Registratie Mislukt",
	"offhook":"Hoorn opgenomen",
	"onhook":"Hoorn neergelegd",
	"incoming_call":"Inkomend Gesprek",
	"outgoing_call":"Uitgaande Gesprek",
	"call_established":"Verbonden",
	"call_terminated":"Afgebroken",
	"open_dnd":"DND aan",
	"close_dnd":"DND uit",
	"open_always_forward":"Direct doorschakelen aan",
	"close_always_forward":"Direct doorschakelen uit",
	"open_busy_forward":"Doorschakelen bij bezet aan",
	"close_busy_forward":"Doorschakelen bij bezet uit",
	"open_no_busy_forward":"Doorschak. bij niet opnemen aan",
	"close_no_busy_forward":"Doorschak. bij niet opnemen uit",
	"transfer_call":"Gesprek doorschakelen",
	"blind_trandfer_call":"Doorverbinden zonder ruggespraak",
	"attended_trandfer_call":"	Doorverbinden met ruggespraak",
	"hold":"Wacht",
	"unhold":"In wacht zetten uitgeschakeld",
	"mute":"Mute",
	"unmute":"Mute uitgeschakeld",
	"missed_call":"Gemist gesprek",
	"idle_tobusy":"Idle To Busy",
	"busy_toldel":"Busy To Idle",
	"forwardincomingcall":"Gesprek doorschakelen",
	"rejectincomingcall":"Oproep weigeren",
	"answernewincomingcall":"Beantwoord inkomende oproep",
	"transferfinished":"Doorverbonden",
	"transferfailed":"Doorverbinden mislukt",
	"unselected":"Niet geselecteerd",
	"softkeysunselected":"Softtoets niet geselecteerd",
	"softkeys":"Softtoetsen",
	"reloace_rule":"Regel vervangen",
	"dial_now":"Kies nu",
	"area_code":"Netnummer",
	"block_out":"Blokkeren",
	"index":"Index",
	"prefix":"Voorvoegsel",
	"replace":"Vervang",
	"dial_now_rule":"Kies nu regel",
	"code":"Code",
	"min_length":"Min Lengte",
	"max_length":"Max Lengte",
   //"accountaccount":"AccountAccount",
	"block_out_number1":"Blokkade nummer 1",
	"block_out_number2":"Blokkade nummer 2",
	"block_out_number3":"Blokkade nummer 3",
	"block_out_number4":"Blokkade nummer 4",
	"block_out_number5":"Blokkade nummer 5",
	"block_out_number6":"Blokkade nummer 6",
	"block_out_number7":"Blokkade nummer 7",
	"block_out_number8":"Blokkade nummer 8",
	"block_out_number9":"Blokkade nummer 9",
	"block_out_number10":"Blokkade nummer 10",
	"phonebook_url":"Telefoonboek URL",
    //contacts
	"url":"URL",
	"name":"Naam",
	"contact":"Contact",
	"ldap_name_filter":"LDAP naam filter",
	"ldap_number_filter":"LDAP nummer filter",
	"server_address":"Server adres",
	"base":"Basis DN",
	"max_hits":"Max.Hits (1~32000)",
	"ldap_name_attributes":"LDAP Naam Attributen",
	"ldap_number_attributes":"LDAP Nummer Attributen",
	"ldap_display_name":"LDAP Display Naam",
	"protocol":"Protocol",
	"search_delay":"Zoek vertraging (0~2000ms)",
	"ldap_lookup_for_incoming_call":"LDAP-opzoeken voor inkomende oproep",
	"ldap_storing_results":"LDAP Sorteren Resultaat",
	"ldap_lookup_for_dial":"LDAP-opzoeken voor kiezen",
	"broadsoft_item":"BroadSoft Item",
	"displayname":"Display Naam",
	"callog_item":"Oproeplogboek Item",
	"version2":"Versie 2",
	"version3":"Versie 3",
	"blacklist":"BlackList",
	"hangup":"Ophangen",
	"display_name":"Display Naam",
	"officenumber":"Werk Nummer",
	"mobilenum":"Mobiel Nummer",
	"othernumber":"Ander Nummer",
	"other_set":"Anderen",
	"empty":"Leeg",
	"nico":"Nico",
	"wemma":"wEmma",
	"william":"William",
	"group":"Groep",
	"photo":"Afbeelding",
	"groupinfo":"Groep Info",
	"select_import_file":"Selecteer import bestand",
	"show_title":"Toon Titel",
	"call_panel":"Call Panel",
	"dial_a_number":"Kies een nummer",
	"outgoing_identity":"Uitgaande identiteit",
	"dialed_list":"Gekozen nummers",
	"missed_list":"Gemiste oproepen",
	"received_list":"Ontvangen oproepen",
	"forwarded_list":"Doorgesch. nummers",
	"local_identity":"Lokale identiteit",
	"contact_UploadPhoto":"Upload afbeelding",
    // ------------------- Directory: preview   start------------------- //
	"preview":"Voorbeeld",
	"preview_DelOldcontact":"DelOldcontact",
	"preview_on":"Aan",
	"preview_off":"Uit",
    //------------------- Directory:  preview  end  -------------------//
    // ------------------- Directory: Call History   start------------------- //
	"call_history":"Oproeplijst",
	"tel_number":"Tel. Nummer",
    //------------------- Directory: Call History  end  -------------------//
    // security
    //"indexindex":"IndexIndex",
	"issued_to":"Uitgegeven aan",
	"issued_by":"Uitgegeven door",
	"expiration":"Vervaltijd",
	"del":"Del",
	"only_accept_trusted_certificates":"Accepteer alleen vertrouwde certificaten",
	"import_trusted":"Vertrouwd certificaat importeren (.cer)",
	"load_form_file":"Laad formulier bestand:",
	"upload_server_certificate":"Upload Server Certificaat",
	"note":"Help",
	"version_right":"Versie",
	"basic":"Basic",
	"codecs":"Codecs",
	"key_type":"Toets Type",
	"blf":"BLF",
	"user_type":"Gebruikers Type",
	"reset_to_factor_settin":"Reset",
	"remote_phone_book":"Extern Telefoonboek",
	"cng":"CNG",
	"jitter_buffer":"JITTER BUFFER",
	"select_country":"Selecteer Land",
	"sms_number":"SMS Nummer",
	"answer_or_reject":"Beantwoorden of Weigeren",
    //"swich":"Swich",
	"digit":"Digit 0-9*",
	"digit_digit":"[digit-digit]",
	"digit_digit_digit":"[digit-digit,digit]",
	"x":"x",
	"dian":".",
	"add_contact":"Toevoegen Contact/Blacklist",
	"delete_contact":"Wissen Contact/Blacklist",
	"move_to_contact":"Verplaats naar Contact/blacklist",
	"contact_export":"Exporteer",
	"contact_import":"Importeer",
	"status_font1":"Het toont producttype en de versie van firmware.",
	"status_font2":"Het toont de gedetailleerde informatie van WAN-poort en LAN-poort.",
	"status_font3":"Het toont de geregistreerde status van de accounts.",
	"status_font4":"Het toont de looptijd na het opstarten van het apparaat.",
	"status_font5":"Herstart de voip-toepassing opnieuw op",
    //Profile
	"account_font5":"De basisparameters die door de beheerder zijn geconfigureerd.",
	"account_font6":"Selecteer de codec die u wilt gebruiken.",
	"account_font7":"De geavanceerde parameters die door de beheerder zijn geconfigureerd.",
	"basic_font1":"De telefoon krijgt de netwerkconfiguratie van een DHCP-server.",
	"basic_font2":"Voer het IP-adres, het subnetmasker, het standaard gatewayadres en de primaire en secundaire DNS-adressen handmatig in",
	"basic_font3":"Controleer alstublieft bij uw netwerkbeheerder of serviceprovider voordat u deze instelling wijzigt",
	"advanced_font1":"Een VLAN is een logisch lokaal netwerk (of LAN) dat zich uitstrekt over een enkel traditioneel LAN naar een groep LAN segmenten, gegeven specifieke configuraties.",
	"advanced_font2":"Als er onvoldoende netwerkcapaciteit is, kan QoS-prioriteit worden verschaft door de waarde voor de gebruiker in te stellen.",
	"advanced_font3":"Definieer de poort voor spraakoverdracht.",
    //ddskey
	"memorykey_font1":"Algemene functie toets type: Snelkeuze, BLF, Call-park, intercom ...",
	"memorykey_font2":"Deze BLF instelling vereist een herstart van het toestel",
	"extkey_font1":"Algemene functie toets Type: Snelkeuze, BLF, Call-park, intercom ...",
	"extkey_font2":"Hiermee kan de knop worden geconfigureerd als een Busy Line Field (BLF) functie voor een gespecificeerd account. Deze functie moet door de server worden ondersteund.",
	"preference_font1":"Selecteer de tijdzone van uw locatie.",
	"preference_font2":"De tijdserver die wordt gebruikt om de klok van de telefoon te synchroniseren.",
	"preference_font3":"U kunt alleen afbeeldingen uploaden met de extentie '.bmp' en '.jpg'.",
	"upgrade_font1":"Toon de informatie van de twee systeemafbeeldingversies.",
	"upgrade_font2":"Reset alle telefooninstellingen naar hun standaardconfiguratie (Opmerking: dit zal alle bestaande instellingen overschrijven!)",
	"upgrade_font3":"Start de voip-toepassing opnieuw op.",
	"upgrade_font4":"Start het telefoonsysteem opnieuw op.",
	"features_font1":"Deze functie kan de inkomende oproep doorverbinden naar het bestemmingsnummer.",
	"features_font2":"Bestemmingsnummer naar waar u wilt doorsturen.",
	"features_font3":"De code die wordt verzonden naar de PBX (server) wanneer de telefoon is ingeschakeld",
	"features_font4":"De code die wordt verzonden naar de PBX (server) wanneer de telefoon is uitgeschakeld",
	"autoprovision_font1":"Configureer gedetailleerde instellingen voor het updaten van firmware",
	"autoprovision_font2":"Configureer gedetailleerde instellingen voor het .xml-formaat telefoonboek dat wordt gedownload van de auto provisioning server",
	"configuration_font1":"U kunt het configuratiebestand van de telefoon opslaan in een back-up lokatie, en ook weer een back-up configuratiebestand herstellen",
	"configuration_font2":"Er zijn twee manieren om het systeemlogboek te exporteren: download direct of download via de Syslog-server",
    "remote_phonebook_font1":"Gebruik deze functie om de contactpersoon van de telefoon van de server te downloaden. U moet de URL van het telefoonboekbestand opgeven (bijvoorbeeld: http://<server IP-adres>/phonebook.xml - men kan ook https:// gebruiken) en de naam van het telefoonboek in het veld Naam hernoemen.",
	"voice_font1":"Voice Activity Detectie.",
	"voice_font2":"Comfort Noise Generatie.",
	"voice_font3":"Een gedeeld gegevensgebied waar spraakpakketen kunnen worden verzameld, opgeslagen en gelijkmatig naar de voice processor gestuurd",
	"tones_font1":"Selecteer uw land om de standaard kiestonen te genereren. Of selecteer 'Gebruiker' om de kiestonen aan te passen.",
	"sms_font1":"Voer het telefoonnummer in waar u een bericht naar stuurt en geef de inhoud van het bericht in.",
	"softkey_font1":"Het zal beschikbaar zijn als er een inkomend gesprek is.",
	"softkey_font2":"Het zal alleen beschikbaar zijn als er twee of meer actieve gesprekken zijn.",
	"dial_font1":"Identificeert een specifiek cijfer (gebruik geen # omdat deze is gedefinieerd als zend toets).",
	"dial_font2":"Identificeert een gekozen cijfer dat in het bereik is opgenomen.",
	"dial_font3":"Specificeert een bereik als een komma gescheiden lijst.",
	"dial_font4":"Past op een enkel cijfer/teken dat wordt gekozen.",
	"dial_font5":"Past een willekeurig aantal cijfers aan.",
	"dial_font6":"Minimale lengte van het lokale nummer.",
	"dial_font7":"Maximale lengte van het lokale nummer.",
    "remotephone_font1":"Met deze functie kunt u de contactlijst van de server downloaden. U moet de telefoonboeklijst-URL invoeren (bijvoorbeeld: http://<server IP-adres>/./phonebook.xml) en de naam van het telefoonboek in het veld Naam.",
	"contact_font1":"Vul de contactgegevens in. Het veld met 'Naam' mag niet leeg zijn!",
	"contact_font2":"Selecteer een contactpersoon of meerdere contactpersonen en druk op de knop 'Wis' om deze te verwijderen.",
	"contact_font3":"Selecteer een contactpersoon of meerdere contactpersonen en druk op de knop 'Verplaats naar Contact/Blacklist' om deze te verplaatsen.",
	"contact_font4":"Blader door .xml en .csv-indelingsbestand en import.",
	"contact_font5":"Klik op de Export knop, dan wordt het bestand phonebook.xml of phonebook.csv gedownload.",
	"contact_font6":"Het formaat van de ondersteunende afbeelding is jpg of bmp, en de grootte dient minder dan 128 bij 128 pixels te zijn",
    //security
	"password_font1":"Als u zich aanmeldt als beheerder, kunt u het wachtwoord van de beheerders hier wijzigen.",
	"password_font2":"U kunt hier het TLS-certificaatbestand importeren.",
	"copyright":"Copyright © 2005-2017 Alle Rechten Voorbehouden",
	"question_mask125":"In seconden betekent 0 nooit achtergrondverlichting uit, standaard is 0 seconden",
	"memory_free":"Geheugen vrij",
	"logo_only":"alleen logo",
	"text_logo":"Tekst Logo",
	"question_mask126":"Dit zal alleen werken wanneer het screensaver type 'Tijd & Logo' is of alleen 'Logo', ';' is volgende regel",
	"min":"Minutes",
	"question_dhcp_vlan":"DHCP optie 132",
	"dhcp_vlan":"DHCP VLAN",
	"feature_key_syn":"Feature Key Sync",
	"all":"Alle",
	"not_in_group":"Niet in de groep",
	"firmware_file_prefix":"Firmware/Config Bestand Voorvoegsel",
	"firmware_file_postfix":"Firmware/Config Bestand Achtervoegsel",
	"config_file_prefix":"Config Bestand Voorvoegsel",
	"config_file_postfix":"Config Bestand Achtervoegsel",
	"customer_set_user_agent":"Handmatig instellen van User Agent",
	"wallpaper":"Achtergrond",
	"RFC2543Hold":"RFC 2543 Hold",
	"speed_dial":"Snelkiezen",
	"blf_list":"BLF List",
	"direct_pickup":"Direkte Pickup",
	"group_pickup":"Groep Pickup",
	"call_park":"Parkeren",
	"group_call_park":"Groep Oproep Parkeren",
	"intercom":"Intercom",
	"dtmp":"DTMF",
	"local_group":"Lokale Groep",
	"xml_group":"XML Groep",
	"xml_browser":"XML Browser",
	"dnd":"DND",
	"redial":"Herkiezen",
	"call_return":"Oproep retourneren",
	"url_record":"URL Record",
	"paging":"Paging",
	"group_listening":"Groep luisteren",
	"public_hold":"Public Hold",
	"private_hold":"Private Hold",
	"hot_desking":"Hot Desking",
	"acd":"ACD",
	"zero_touch":"Zero Touch",
	"menu":"Menu",
	"newsms":"Nieuw SMS",
	"switch_account_up":"Vorig Account",
	"switch_account_down":"Volgend Account",
	"local_phone_book":"Lokaal Telefoonboek",
	"broadsoft_phone_book":"BroadSoft Telefoonboek",
	"xml_phone_book":"XML Telefoonboek",
	"network_call_log":"Netwerk Oproep Log",
	"picture":"afbeelding",
	"all_keys":"Alle Toetsen",
	"menu_key":"Menu Toets",
	"answer_all_only":"Alleen Beantwoorden",
	"snom":"Snom",
	"alert_internal_text":"Onderscheidend Belsignaal Interne Tekst",
	"alert_internal_ringer":"Onderscheidend Belsignaal Intern",
	"alert_external_text":"Onderscheidend Belsignaal Externe Tekst",
	"alert_external_ringer":"Onderscheidend Belsignaal Extern",
	"alert_group_text":"Onderscheidend Belsignaal Groep Tekst",
	"alert_group_ringer":"Onderscheidend Belsignaal Groep",
	"expansion_key":"Uitbreidingsmodule",
	"Pre_Page":"Vorige Pagina",
	"Next_Page":"Volgende Pagina",
	"self_host":"Gelijk als Server",
	"exp_server_addr":"Uitbreidingsmodule Upgrade URL",
	"exp_key1":"Module 1",
	"exp_key2":"Module 2",
	"exp_key3":"Module 3",
	"exp_key4":"Module 4",
	"exp_key5":"Module 5",
	"exp_key6":"Module 6",
	"exp_key_1":"Toets 1",
	"exp_key_2":"Toets 2",
	"exp_key_3":"Toets 3",
	"exp_key_4":"Toets 4",
	"exp_key_5":"Toets 5",
	"exp_key_6":"Toets 6",
	"exp_key_7":"Toets 7",
	"exp_key_8":"Toets 8",
	"exp_key_9":"Toets 9",
	"exp_key_10":"Toets 10",
	"exp_key_11":"Toets 11",
	"exp_key_12":"Toets 12",
	"exp_key_13":"Toets 13",
	"exp_key_14":"Toets 14",
	"exp_key_15":"Toets 15",
	"exp_key_16":"Toets 16",
	"exp_key_17":"Toets 17",
	"exp_key_18":"Toets 18",
	"exp_key_19":"Toets 19",
	"exp_key_20":"Toets 20",
	"exp_version":"Uitbreidingsmodule Versie",
	"exp_module_1":"Uitbreidingsmodule 1",
	"exp_module_2":"Uitbreidingsmodule 2",
	"exp_module_3":"Uitbreidingsmodule 3",
	"exp_module_4":"Uitbreidingsmodule 4",
	"exp_module_5":"Uitbreidingsmodule 5",
	"exp_module_6":"Uitbreidingsmodule 6",
	"phone_exp_version":"Versie op toestel",
	"exp_version_detail":"Firmware-versie van de aangesloten uitbreidingsmodule en uitbreidingsmodule firmwareversie opgeslagen op de telefoon",
	"registered":"Geregistreerd",
	"planet_ddns":"DDNS Instellingen",
	"question_mask127":"Deze naam wordt op het LCD-scherm van het apparaat weergegeven",
	"question_mask128":"Optioneel, gebruik deze als de Failover SIP Server geen antwoord geeft",
	"refresh_callerid_via_contact":"Refresh Caller ID Via Contact",
	"dial_when_screensaver":"Kies eerste cijfer",
	"wake_up":"De-activatie van Screensaver",
	"wake_up_and_dial":"De-activatie van Screensaver en maak oproep",
	"headset_priority":"Headset Prioriteit",
	"use_speaker":"Gebruik Luidspreker",
	"use_headset":"Gebruik Headset",
	"ringer_device_for_headset":"Apparaat voor Belsignaal met headset aangesloten",
	"delete_unifont":"Verwijder Font Bestand",
	"consult_admin":"(Raadpleeg uw systeembeheerder of netwerk beheerder)",
	"dial_now_timeout":"Kies Nu Time-out (seconden)",
	"question_mask129":"In seconden, Interval voor 'Kies Nu', standaard is 0 seconden",
	"multicast_paging":"MultiCast Paging",
	"multicast_paging_listen_addr":"Multicast Paging Luister Addr",
	"sip_send_mac":"SIP verstuur MAC",
	"upload_wallpaper":"Upload Achtergrond",
	"wallpaper_delete":"Verwijder Achtergrond",
	"wallpaper_note":"Bestandsnaam dient te bestaan uit letters, cijfers of onderstrepen '_' en het nummer mag niet hoger zijn dan 6.",
	"choose8":"iLBC",
	"ilbc_mode":"iLBC mode",
	"mode20":"20ms mode",
	"mode30":"30ms mode",
	"ilbc_pt":"iLBC Payload Type",
	"ilbc_pt_question":"iLBC Payload, waarde van 96 tot 127, de standaard waarde is 97",
	"choose9":"OPUS",
	"opus_pt":"OPUS Payload Type",
	"opus_pt_question":"OPUS Payload, waarde van 96 tot 127, de standaard waarde is 120",
	"paging_barge":"Paging Barge",
	"paging_priority_active":"Paging Priority Aktief",
	"listening_address":"Luisteren op adres",
	"multi_priority":"Multi Prioriteit",
	"ip_address_1":"IP Adres 1",
	"ip_address_2":"IP Adres 2",
	"ip_address_3":"IP Adres 3",
	"ip_address_4":"IP Adres 4",
	"ip_address_5":"IP Adres 5",
	"ip_address_6":"IP Adres 6",
	"ip_address_7":"IP Adres 7",
	"ip_address_8":"IP Adres 8",
	"ip_address_9":"IP Adres 9",
	"ip_address_10":"IP Adres 10",
	"max_rtp_port":"Max RTP Poort",
	"min_rtp_port":"Min RTP Poort",
	"custom":"Aangepast",
	"australia":"Australi&euml;",
	"austria":"Oostenrijk",
	"brazil":"Brazili&euml;",
	"belgium":"België",
	"china":"China",
	"chile":"Chili",
	"czech":"Tsjechië",
	"denmark":"Denemarken",
	"finland":"Finland",
	"france":"Frankrijk",
	"germany":"Duitsland",
	"great_britain":"Groot Brittanni&euml;",
	"greece":"Griekenland",
	"hungary":"Hongarije",
	"lithuania":"Litouwen",
	"india":"India",
	"italy":"Itali&euml;",
	"japan":"Japan",
	"mexico":"Mexico",
	"new_zealand":"Nieuw-Zeeland",
	"netherlands":"Nederland",
	"norway":"Noorwegen",
	"portugal":"Portugal",
	"spain":"Spanje",
	"switzerland":"Zwitzerland",
	"sweden":"Zweden",
	"russia":"Rusland",
	"united_states":"Verenigde Staten",
	"alert_ring":"Onderscheidend Belsignaal",
	"alert_ring_text":"Onderscheidend Belsignaal Naam ",
	"alert_ring_file":"Onderscheidend Belsignaal Bestand ",
	"redial_mode":"Herkiezen",
	"dial_dir":"Laatst gekozen nummer",
	"dial_select":"Kies laatst gekozen nummer uit lijst",
	"lcd_screen":"LCD Scherm",
	"save_screen":"Opslaan Scherm",
	"tools":"Tools",
	"backup_outbound_proxy":"Backup Uitgaande Proxy",
	"intercom_barge":"Intercom Barge",
	"show_missed_calls":"Toon gemiste oproepen",
	"show_missed_calls_detail":"Of u de gemiste oproepmelding op LCD wilt weergeven",
	"date_time":"Datum&Tijd",
	"start_date":"Start Datum",
	"end_date":"Eind Datum",
	"month":"Maand",
	"voice_msg_status":"VoiceMail Ber. Status",
	"headset_volume":"Headset Send Volume",
	"handset_volume":"Handset Send Volume",
	"handfree_volume":"Handsfree Send Volume",
	"speaker_volume":"Speaker Volume",
	"mic_volume":"Mic Volume",
	"blf_setting":"BLF Inst.",
	"blf_selected_type":"BLF Geselecteerd Type",
	"blf_led_mode":"BLF Led Mode",
	"blf_status_text":"BLF Status Tekst",
	"current_call_status":"Huidige oproepstatus",
	"idle":"Vrij",
	"talking":"Praten",
	"parked":"Geparkeerd",
	"off_line":"Off Line",
	"led_off":"Led Uit",
	"solid_red":"Rood altijd aan",
	"solid_green":"Groen altijd aan",
	"flashing_red_1000":"Knipperend Rood 1s",
	"flashing_red_500":"Knipperend Rood 0.5s",
	"flashing_red_200":"Knipperend Rood 0.2s",
	"flashing_red_100":"Knipperend Rood 0.1s",
	"flashing_green_1000":"Knipperend Groen 1s",
	"flashing_green_500":"Knipperend Groen 0.5s",
	"flashing_green_200":"Knipperend Groen 0.2s",
	"flashing_green_100":"Knipperend Groen 0.1s",
	"current_call_status_font1":"De oproepstatus van de gemonitoorde gebruiker",
	"blf_status_text_font1":"Sleutelwoord toegekend aan de toets voor BLF notify",
	"blf_led_mode_font1":"De LED-modus die u wilt",
	"suppress_dtmf_display":"Onderdruk DTMF Display",
	"suppress_dtmf_display_delay":"Onderdruk DTMF Display vertraging",
	"import_cfg_CA":"Import Certificaten Bestand (Provisioning)",
	"import_cfg_CA_file":"Import Certificaten Bestand (Provisioning)",
	"cfg_certs_file":"TLS-certificaatbestand (Provisioning)",
	"backup_ntp_server":"Backup NTP Server",
	"backup_ntp_server_help":"Stel de backup NTP-server in om de tijd te verkrijgen",
	"voice_mail_tone":"Voice Mail Toon",
	"auto_redial":"Automatisch Opnieuw Kiezen",
	"auto_redial_interval":"Automatisch Opnieuw Kiezen Interval (1~300s)",
	"auto_redial_times":"Automatisch Opnieuw Kiezen aantal (1~300)",
	"busy_tone_timer":"Ingesprekstoon Timer (0~5s)",
	"Auto_logout_time":"Auto Loguit Tijd (1 ~ 5000 min)",
	"Reboot_in_talking":"Herstart tijdens gesprek",
	"delete":"Wis",
	"device_certificate":"Apparaatcertificaten",
	"default_certificate":"Standaardcertificaten",
	"custom_certificate":"Aangepaste certificaten",
	"trusted_certificates":"Vertrouwde certificaten",
	"all_certificates":"Alle certificaten",
	"vq_rtcp_report":"VQ RTCP Report",
	"vq_report_collector":"Voice Quality Report Collector",
	"rtcp_xr_report_format":"RTCP-XR Report Formaat",
	"rtcp_support":"RTCP Support",
	"exp_server_setting":"Uitbreidingsmodule Server",
	"autoprovision_now":"Autoprovisioning direct",
	"do_not_check":"Geen controle",
	"always_check":"Altijd controleren",
	"automatic":"Automatisch",
	"ring_server_path":"Belsignaal Server URL",
	"language_server_url":"Taal Server URL",
	"hlpres_server_url":"hlpres Server URL",
	"exp_res_server_url":"exp_res Server URL",
	"VPN_server_url":"VPN Server URL",
	"cert_ca_8021x_url":"8021x CA cert URL",
	"cert_dev_8021x_url":"8021x DEV cert URL",
	"TCA_server_url":"Vertrouwde CA Server URL",
	"SCA_server_url":"Server CA Server URL",
	"screensaver_server_url":"Screensaver Server URL",
	"wallpaper_server_url":"Achtergrond afbeelding Server URL",
	"Exp_ScreenSaver_Url":"Uitbr. Screensaver URL",
	"backlight_inactive_level":"Achtergrondverlichting In-aktief Nivo",
	"backlight_active_level":"Achtergrondverlichting Aktief Nivo",
	"permission_denied":"Geen toestemming!",
	"newcall":"Nieuw Oproep",
	"zero_active":"Zero Active",
	"wait_time":"Wacht Tijd (1~100s)",
	"zero_touch_type":"Zero Touch Type",
	"ehs":"EHS",
	"normal":"Normaal",
	"internet_port":"Internet Poort",
	"ip_mode":"IP Mode (IPv4/IPv6)",
	"ipv4":"IPv4",
	"ipv6":"IPv6",
	"ipv4_ipv6":"IPv4&IPv6",
	"ipv6_prefix":"IPv6 Voorvoegsel (0~128)",
	"static_dns_v6":"IPv6 Statisch DNS",
	"three_way_call_release_type":"Drie-Way Call Release Type",
	"hung_up":"Opgehangen",
	"visual_alert":"Visual Alert",
	"ehs_version":"EHS Versie",
	"ehs_model_version":"EHS Module Versie",
	"detect_ip_conflict":"Detecteer IP Conflict",
	"xsi_info":"XSI Infomatie",
	"allow_sa_for_xsi":"Toestaan SIP Authenticatie voor XSI",
	"host_server":"Host Server",
	"xsi_server_type":"XSI Server Type",
	"http":"HTTP",
	"https":"HTTPS",
	"uc_username":"UC Gebruikersnaam",
	"uc_password":"UC Wachtwoord",
	"enterprise":"Enterprise",
	"enterprise_common":"Enterprise Algemeen",
	"group_common":"Groep Algemeen",
	"personal":"Persoonlijk",
	"custom_dir":"Aangepast telefoonboek",
	"call_logs":"Oproeplogboek",
	"enable_custom_dir":"Inschakelen aangepast telefoonboek",
	"network_call_logs":"Netwerk Oproep Log",
	"phonebook_url_1":"remote phonebook 1",
	"phonebook_url_2":"remote phonebook 2",
	"phonebook_url_3":"remote phonebook 3",
	"phonebook_url_4":"remote phonebook 4",
	"phonebook_url_5":"remote phonebook 5",
	"sub_exp":"Registratie verloopt",
	"sca_barge_in":"SCA Barge-In",
	"speeddial_detect_digitmap":"Snelkies detecteer Digitmap",
	"check_syn_with_auth":"Controleer Sync met Authenticatie",
	"Callback":"Terugbellen",
	"Callback_code":"Terugbellen Code",
	"Synchronize_time":"LDAP Synchronisatie Tijd (0~9999min.)",
	"Sync_time_detail":"in minuten, 0 betekend nooit synchroniseren, standaard is 0",
	"port_link":"Poort Link",
	"wan_speed":"WAN Poort link snelheid",
	"wan_s_auto0":"auto onderhandelen",
	"wan_s_10H":"10M half duplex",
	"wan_s_10F":"10M full duplex",
	"wan_s_100H":"100M half duplex",
	"wan_s_100F":"100M full duplex",
	"wan_s_1000F":"1000M full duplex",
	"lan_link":"PC Poort Aktief",
	"lan_link0":"auto onderhandelen",
	"sip":"SIP",
	"sip_t1_timer":"SIP Sessie Timer T1 (0.5~10s)",
	"sip_t2_timer":"SIP Sessie Timer T2 (2~40s)",
	"sip_t4_timer":"SIP Sessie Timer T4 (2.5~60s)",
	"both":"Luidspreker & Headset",
	"eap_peap_mschapv2":"EAP-PEAP/MSCHAPV2",
	"eap_ttls_mschapv2":"EAP-TTLS/EAP-MSCHAPV2",
	"eap_peap_gtc":"EAP-PEAP/GTC",
	"eap_ttls_gtc":"EAP-TTLS/EAP-GTC",
	"eap_fast":"EAP-FAST",
	"download_user_Bin_configuration":"Download de configuratie (BIN) van de gebruiker",
	"delete_user_configuration":"Verwijder Gebruiker Configuratie",
	"download_user_bin":"Download BIN Bestand",
	"delete_user_file":"Verwijder BIN Bestand",
	"lcd_gray_level":"LCD grijs nivo",
	"DST_Type":"DST Type",
	"DST_day":"Dag Type",
	"DST_week":"Week Type",
	"Start_week":"Start Week",
	"End_week":"Einde Week",
	"play_hold_tone":"Weergeven Hold Toon",
	"play_hold_tone_delay":"Weergeven Hold Toon Vertraging",
	"sip_date_overide_time":"SIP mag Datum/Tijd overschrijven",
	"layer_3_qos_sip":"SIP QoS",
	"layer_3_qos_rtp":"Spraak QoS",
	"Upgrade_EXP_Rom":"Upgraden Firmware Uitbreidingsmodule",
	"cdp":"CDP",
	"cdp_range":"(1~3600s)",
	"Ldap_name_attri":"LDAP Naam Attributen",
	"Ldap_number_attri":"LDAP Nummer Attributen",
	"Ldap_name_attri_note":"De naam attributen van elk record worden door de LDAP-server geretourneerd.",
	"Ldap_number_attri_note":"De nummer attributen van elk record worden door de LDAP-server geretourneerd",
	"dsskey_speaker":"Speaker",
	"dsskey_headset":"Headset",
	"dsskey_vm":"Voicemail",
	"dsskey_menu":"Menu",
	"dsskey_menu_pin":"Menu met PIN",
	"dsskey_volumeup":"Vol.Omh.",
	"dsskey_volumedown":"Vol.Oml.",
	"logo_led":"Logo LED",
	"tie_to_backlight":"Volg Achtergrond",
	"always_on":"Altijd Aan",
	"always_off":"Altijd Uit",
	"buddies":"Buddies",
	"my_status":"Mijn Status",
	"uc_favorite":"UC Favoriet",
	"enable_auto_favorite":"Inschakelen Auto Favoriet",
	"exp_backlight_level":"Uitbreidingsmodule Achtergrond Nivo",
	"lable_scroll":"Label Scroll",
	"security_classification":"Security",
	"recording":"Recording",
	"softkey_layout_url":"Softtoets Layout URL",
	"rphonebook_loadtime":"Update Tijd Interval (minuten)",
	"rphonebook_loadtime_question":"Integer from 60 to 10080",
	"popups":"Popups",
	"missed_call_popup":"Gemiste oproepen Popup",
	"forward_call_popup":"Doorgeschakelde oproepen Popup",
	"voice_mail_popup":"Voice Mail Popup",
	"text_message_popup":"Tekst Bericht Popup",
	"color_popup_style":"Popup Style",
	"remote_control":"Externe Controle",
	"push_xml_server_ip":"Push XML Server IP",
	"sip_notify":"SIP Notify",
	"strvpnpcapbtn":"VPN pcap",
	"port_mirror":"PC Poort Mirror",
	"lcd_language":"Display taal",
	"lcd_language_why":"Kies de juiste display taal van het toestel",
	"ring_yinliang":"Belsignaal Volume",
	"yinliang_question":"Tussen de 0 en 14",
	"dnd_work_type":"DND Mode",
	"dnd_sync_mode":"DND Sync Mode",
	"call_pickup_mode":"Oproep Pickup Mode",
	"xsi":"BroadSoft XSI",
	"fac":"Feature Code",
	"call_park_mode":"Oproep Parkeer Mode",
	"direct_call_park_show":"Toon Direkt Oproep Parkeren",
	"direct_call_park_code":"Direkt Oproep Parkeer Code",
	"group_call_park_show":"Toon Groep Oproep Parkeren",
	"direct_call_park":"Direkt Oproep Parkeer",
	"group_call_park_code":"Groep Oproep Parkeer Code",
	"park_retrieve_code":"Uitparkeer Code",
	"visual_alert_4_call_park":"Visuele waarschuwing voor geparkeerde oproep",
	"audio_alert_4_call_park":"Audio waarschuwing voor geparkeerde oproep",
	"dnscache":"DnsCache",
	"DNSCache":"DNS-cache",
	"domain":"Domein",
	"IP_Address":"IP Adress",
	"endcall":"Ophangen",
	"g_park":"Groepspark",
	"d_park":"Direct Park",
	"callwaiting":"Wisselgesprek",
	"ng_all_contacts":"Alle contacten",
	"line_key_as_cancel":"Lijn toets als annuleren",
	"pound_as_23":"Vervang # voor %23",
	"question_pound_as_23":"Vervang # voor %23 wanneer er nummers worden gekozen",
	"sip_message_format":"Oproep bericht indeling",
	"sip_regular":"Regulier",
	"sip_user_phone":"User=Phone",
	"sip_tel":"Tel",
	"cur_sip_server":"Huidige SIP Server",
	"dhcp_sip_server":"DHCP SIP Server",
	"display_default_account":"Toon standaard account",
	"call_completion":"Oproep voltooiing",
	"enable_call_completion":"Inschakelen oproep voltooiing",
	"aul":"Toestaan vanaf IP adressen",
	"send_mac_in_useragent":"MAC toevoegen aan User-Agent",
	"question_send_mac_in_useragent":"In- of uitschakelen van MAC adres in User-Agent",
	"callpark_retrive":"Oproep terughalen uit park.",
	"common_name_validation":"Algemene Naam Validatie",
	"wan_port_dis":"WAN Poort",
	"Upload_Cfg_server_path":"Configuration Upload server path",
	"Check_sync_reboot":"Controleer-sync reboot",
	"directory_search_time_out":"Tel.boek zoek time-out",
	"directory_search_mode":"Tel.boek zoek mode",
	"prefix_mode":"Prefix mode",
	"fuzzy_mode":"Fuzzy mode",
	"lcd_font_size_control":"LCD Font Groote",
	"lcd_font_size_normal":"Normaal",
	"lcd_font_size_large":"Groot",
	"call_id_font_size":"CLIP Font Groote",
	"call_id_font_size_auto":"Auto",
	"sip_error_prompt":"SIP fout Prompt",
	"history_smart_dial":"Historie Smart Kiezen",
	"sip_url_call":"SIP URL-oproep",
	"resolve_url_domain":"Resolve URL-domein",
	"dhcp_option_100":"DHCP Optie 100",
	"dhcp_option_120":"DHCP Optie 120",
	"pullcall":"Pull Call",
	"pullcallCode":"Pull Call Code",
	"linekeyPagePre":"Vorige Lijntoets pagina",
	"linekeyPageNext":"Volgende Lijntoets pagina",
	"dtmf_combined":"Gecombineerd",
	"choose10":"Geen",
	"contacts_photo_server":"Contacten Fotoserver",
	"blf_blink":"Knipperen BLF label",
	"transfer_release_setting":"Transfer Release Trigger:",
	"notify200":"NOTIFY met 200OK",
	"refer2xx":"2xx antwoord van REFER",
	"byebye":"BYE voor de oproep",
	"HttpGetFile_Waittime":"HTTP GET Bestand wachttijd",
	"selective":"Selectief",
	"entry":"Ingave",
	"question_mask_selectivecf":"Het inkomende nummer dat wordt doorgestuurd",
	"g726_32_cucstom_onoff":"Aangepast G726_32 Payload Type",
	"g726_32_custom_onoff_question":"Bij uitschakeling van deze optie is het payload-type van g726_32 sdp in uitgaande oproep type 2. Deze instelling heeft geen invloed op de onderhandeling over deze codec van inkomende oproepen (elk type payload van g726_32 wordt ondersteund).",
	"g726_32_pt":"G726_32 Payload Type",
	"g726_32_pt_question":"van 96 tot 127, standaard waarde is 111",
	"mute_type":"Mute Type",
	"comfort_noise":"Comfoort ruis",
	"zero_payload":"Zero Payload",
	"stop_rtp_send":"Stop RTP Zenden",
	"metaswitch":"MetaSwitch",
	"bw_xsi":"Broadsoft XSI",
	"bw_fac":"Feature Code",
	"IdleAcdLoginOut":"Idle ACD Login/out",
	"MixedAcdLoginOut":"Mixed ACD Login/out",
	"IdleAcdUnAvailable":"Idle ACD Un/Available",
	"AcdDispositionCode":"ACD Disposition Code",
	"AcdTrace":"ACD Trace",
	"GuestInOut":"Guest In/Uit",
	"FlexGuestInOut":"Flex Guest In/Uit",
	"IdleMenu":"Idle Menu",
	"IdleHistory":"Idle History",
	"IdleDirectory":"Idle Directory",
	"IdleDnd":"Idle DND",
	"IdleBroadSoftPhonebook":"Idle BroadSoft Phonebook",
	"IdleNetworkCalllog":"Idle Network Calllog",
	"line_selected_type":"BLF Account Type",
	"current_line_status":"Huidige lijnstatus",
	"current_line_status_font1":"De lijnstatus van het geregistreerde account",
	"line_led_mode":"Lijn LED mode",
	"line_led_mode_font1":"De LED-knipperende modus die u wilt gebruiken voor de geselecteerde functie",
	"account_disabled":"Disabled",
	"account_register_failed":"Registratie Mislukt",
	"account_not_registered":"Not Geregistreerd",
	"account_registered":"Geregistreerd",
	"dnd_no":"No",
	"dnd_yes":"Yes",
	"device_type_router":"Router",
	"device_type_bridge":"Bridge",
	"device_type_expansion":"Expansion",
	"line_current_status":"Huidige lijnstatus",
	"line_setting":"Lijn Inst.",
	"line_unregistered":"Niet Geregistreerd",
	"line_registered":"Geregistreerd",
	"line_ringing":"Overgangstoon",
	"line_talk":"Verbinding",
	"line_hold":"Wacht",
	"automaticallyExpPriority":"Automatisch Uitbr. Module",
	"Account":"Account",
